### ISSUE TITLE
Trying to install with the "^0" for Laravel 8 but getting error

### ISSUE THREAD

**Issue by genechuah** [korridor/laravel-has-many-merged#10] opened 2023-03-18 16:47 UTC
What I did : `composer require korridor/laravel-has-many-merged "^0"`

What happened :
```
./composer.json has been updated
Running composer update korridor/laravel-has-many-merged
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires korridor/laravel-has-many-merged == 0.0.0.0, found korridor/laravel-has-many-merged[dev-feature/laravel_10, dev-main, 0.0.1, 0.0.2, 0.0.3, 1.0.0] but it does not match the constraint.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

Your help would be greatly appreciated!

**Comment by korridor** [comment] 2023-03-19 18:22
Thanks for your issue!

I just tried this myself, and it works for me. Can you please send me your composer version and the version of the PHP binary that composer uses?

**Comment by genechuah** [comment] 2023-03-19 18:43
Thanks. I decided instead to just use ->union() on Relations (hasMany) to achieve what I needed.
But for reference :
Composer 2.2.5
PHP 7.4.4

**Comment by korridor** [comment] 2023-03-19 19:10
Ok, I just tried to reproduce it with the official composer and a legacy image I found that uses PHP 7.4, but I cannot reproduce the error.

```bash
docker run -it composer:2.2.5 composer require korridor/laravel-has-many-merged "^0"
docker run -it lucor/composer composer require korridor/laravel-has-many-merged "^0"
```

Since you probably don't want to try it again with more debugging, as you already found another solution, I will close the issue for now.

**Closed as completed by korridor** 2023-03-19 19:10 UTC
